package com.example.ui

import android.widget.Toast
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ui.theme.*

@Composable
fun RoomVisualizerTab(viewModel: SalesViewModel) {
    val context = LocalContext.current
    var roomType by remember { mutableStateOf("Living Room") } // Living Room, Master Bedroom, Executive Office, Dining Hall
    var roomWidth by remember { mutableStateOf("5.5") } // meters
    var roomLength by remember { mutableStateOf("6.0") } // meters
    var wallColor by remember { mutableStateOf("Warm Ivory") }
    var detectedWalls by remember { mutableStateOf(4) }
    var detectedWindows by remember { mutableStateOf(2) }
    var detectedDoors by remember { mutableStateOf(1) }
    var isAnalyzing by remember { mutableStateOf(false) }
    var layoutGenerated by remember { mutableStateOf(true) }

    val products by viewModel.allProducts.collectAsState()

    LazyColumn(
        modifier = Modifier
            .fillMaxSize()
            .padding(12.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        item {
            Card(
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant),
                shape = RoundedCornerShape(16.dp),
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.SpaceBetween,
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(imageVector = Icons.Default.Build, contentDescription = "Room Visualizer", tint = GoldAccent)
                            Spacer(modifier = Modifier.width(8.dp))
                            Text("AI Room Spatial Visualizer & Layout Advisor", fontSize = 16.sp, fontWeight = FontWeight.Bold, color = GoldAccent)
                        }
                        Surface(
                            color = DarkWalnut,
                            shape = RoundedCornerShape(8.dp)
                        ) {
                            Text("3D AR Engine", modifier = Modifier.padding(horizontal = 8.dp, vertical = 4.dp), fontSize = 10.sp, color = TextLight, fontWeight = FontWeight.Bold)
                        }
                    }

                    Spacer(modifier = Modifier.height(6.dp))
                    Text(
                        "Input room dimensions or scan space photo to detect walls, doors, and generate optimal Bekansi hardwood layout arrangements.",
                        fontSize = 12.sp,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            }
        }

        // Configuration Row
        item {
            Card(
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                shape = RoundedCornerShape(16.dp),
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    Text("Space Specifications", fontSize = 14.sp, fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.onSurface)

                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        listOf("Living Room", "Master Bedroom", "Executive Office", "Dining Hall").forEach { type ->
                            FilterChip(
                                selected = roomType == type,
                                onClick = { roomType = type },
                                label = { Text(type, fontSize = 11.sp) }
                            )
                        }
                    }

                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                        OutlinedTextField(
                            value = roomWidth,
                            onValueChange = { roomWidth = it },
                            label = { Text("Width (m)") },
                            modifier = Modifier.weight(1f)
                        )
                        OutlinedTextField(
                            value = roomLength,
                            onValueChange = { roomLength = it },
                            label = { Text("Length (m)") },
                            modifier = Modifier.weight(1f)
                        )
                    }

                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Button(
                            onClick = {
                                isAnalyzing = true
                                Toast.makeText(context, "Scanning spatial geometry & light vectors...", Toast.LENGTH_SHORT).show()
                                layoutGenerated = true
                                isAnalyzing = false
                            },
                            colors = ButtonDefaults.buttonColors(containerColor = WarmMahogany),
                            shape = RoundedCornerShape(12.dp),
                            modifier = Modifier.height(48.dp)
                        ) {
                            Icon(Icons.Default.Refresh, contentDescription = null, modifier = Modifier.size(18.dp))
                            Spacer(modifier = Modifier.width(6.dp))
                            Text("Simulate Room Scan & Auto-Arrange")
                        }
                    }
                }
            }
        }

        // Room Layout 2D Canvas Visualizer
        item {
            Card(
                colors = CardDefaults.cardColors(containerColor = DarkCocoaBg),
                shape = RoundedCornerShape(16.dp),
                modifier = Modifier
                    .fillMaxWidth()
                    .height(260.dp)
            ) {
                Column(
                    modifier = Modifier
                        .fillMaxSize()
                        .padding(12.dp)
                ) {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text("Top-Down Architectural Plan ($roomWidth m × $roomLength m)", fontSize = 13.sp, fontWeight = FontWeight.Bold, color = TextLight)
                        Text("Detected: $detectedWalls Walls, $detectedWindows Windows, $detectedDoors Door", fontSize = 10.sp, color = GoldAccent)
                    }

                    Spacer(modifier = Modifier.height(8.dp))

                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .weight(1f)
                            .background(Color(0xFF1E140C), shape = RoundedCornerShape(12.dp))
                            .border(1.dp, GoldAccent.copy(alpha = 0.4f), RoundedCornerShape(12.dp))
                            .padding(8.dp)
                    ) {
                        Canvas(modifier = Modifier.fillMaxSize()) {
                            val canvasWidth = size.width
                            val canvasHeight = size.height

                            // Draw room perimeter
                            drawRect(
                                color = GoldAccent.copy(alpha = 0.8f),
                                topLeft = Offset(20f, 20f),
                                size = Size(canvasWidth - 40f, canvasHeight - 40f),
                                style = Stroke(width = 4f)
                            )

                            // Draw Door indicator
                            drawLine(
                                color = AccentWarning,
                                start = Offset(canvasWidth / 2 - 30f, 20f),
                                end = Offset(canvasWidth / 2 + 30f, 20f),
                                strokeWidth = 8f
                            )

                            // Draw Windows indicator
                            drawLine(
                                color = Color(0xFF64B5F6),
                                start = Offset(canvasWidth - 20f, canvasHeight / 3),
                                end = Offset(canvasWidth - 20f, canvasHeight / 3 + 60f),
                                strokeWidth = 8f
                            )

                            // Draw furniture blocks based on room type
                            if (roomType == "Living Room") {
                                // L-Sofa block
                                drawRect(
                                    color = WarmMahogany,
                                    topLeft = Offset(40f, canvasHeight - 110f),
                                    size = Size(140f, 70f)
                                )
                                drawRect(
                                    color = WarmMahogany,
                                    topLeft = Offset(40f, canvasHeight - 170f),
                                    size = Size(60f, 60f)
                                )
                                // Coffee table
                                drawRect(
                                    color = GoldAccent,
                                    topLeft = Offset(120f, canvasHeight - 170f),
                                    size = Size(50f, 40f)
                                )
                                // TV Credenza
                                drawRect(
                                    color = DarkWalnut,
                                    topLeft = Offset(canvasWidth - 140f, 40f),
                                    size = Size(110f, 35f)
                                )
                            } else if (roomType == "Master Bedroom") {
                                // King bed block
                                drawRect(
                                    color = WarmMahogany,
                                    topLeft = Offset(canvasWidth / 2 - 60f, 40f),
                                    size = Size(120f, 140f)
                                )
                                // Nightstands
                                drawRect(
                                    color = GoldAccent,
                                    topLeft = Offset(canvasWidth / 2 - 100f, 40f),
                                    size = Size(30f, 30f)
                                )
                                drawRect(
                                    color = GoldAccent,
                                    topLeft = Offset(canvasWidth / 2 + 70f, 40f),
                                    size = Size(30f, 30f)
                                )
                            } else {
                                // Executive desk block
                                drawRect(
                                    color = WarmMahogany,
                                    topLeft = Offset(canvasWidth / 2 - 70f, canvasHeight / 2 - 40f),
                                    size = Size(140f, 70f)
                                )
                            }
                        }

                        // Legend overlay
                        Column(
                            modifier = Modifier
                                .align(Alignment.BottomEnd)
                                .background(Color.Black.copy(alpha = 0.7f), RoundedCornerShape(8.dp))
                                .padding(6.dp)
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Box(modifier = Modifier.size(10.dp).background(WarmMahogany))
                                Spacer(modifier = Modifier.width(4.dp))
                                Text("Hardwood Furniture", fontSize = 9.sp, color = TextLight)
                            }
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Box(modifier = Modifier.size(10.dp).background(GoldAccent))
                                Spacer(modifier = Modifier.width(4.dp))
                                Text("Accent Tables / Coffee", fontSize = 9.sp, color = TextLight)
                            }
                        }
                    }
                }
            }
        }

        // Recommended Furniture Package & Estimate
        item {
            Card(
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                shape = RoundedCornerShape(16.dp),
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                    Text("AI Recommended Package & Cost Estimate", fontSize = 14.sp, fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.onSurface)

                    val packageItems = when (roomType) {
                        "Master Bedroom" -> listOf(
                            "King Floating Bed 'Sheger' (Grar Acacia)" to 110000.0,
                            "Entoto Forest Sliding Wardrobe" to 145000.0,
                            "Dual Nightstand Set" to 35000.0
                        )
                        "Executive Office" -> listOf(
                            "Executive Desk 'Abay' (Mahogany)" to 95000.0,
                            "Dual-tone Credenza 'Bunna'" to 32000.0,
                            "Ergonomic Leather Chair" to 28000.0
                        )
                        else -> listOf(
                            "Wanza Curved L-Sofa 'Gara'" to 135000.0,
                            "Centerpiece Carved Coffee Table" to 38000.0,
                            "Dual-tone Credenza 'Bunna'" to 32000.0
                        )
                    }

                    var totalEst = packageItems.sumOf { it.second }

                    packageItems.forEach { (item, cost) ->
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(item, fontSize = 12.sp, color = MaterialTheme.colorScheme.onSurface)
                            Text("ETB %,.0f".format(cost), fontSize = 12.sp, fontWeight = FontWeight.Bold, color = GoldAccent)
                        }
                    }

                    HorizontalDivider(modifier = Modifier.padding(vertical = 4.dp))

                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text("Total Estimated Package Cost:", fontSize = 13.sp, fontWeight = FontWeight.Bold)
                        Text("ETB %,.0f".format(totalEst), fontSize = 15.sp, fontWeight = FontWeight.Bold, color = AccentSuccess)
                    }

                    Button(
                        onClick = {
                            Toast.makeText(context, "Generated Package Quotation for $roomType!", Toast.LENGTH_SHORT).show()
                        },
                        colors = ButtonDefaults.buttonColors(containerColor = GoldAccent),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier.fillMaxWidth().height(48.dp)
                    ) {
                        Text("Convert Package to Official Quotation", color = DarkCocoaBg, fontWeight = FontWeight.Bold)
                    }
                }
            }
        }
    }
}
